"""
build_maze_geometry.py - MVP版本
成员A：OpenGL 程序化建模脚本
最小可用实现：只生成v/usemtl/f，确保能被resource_loader读取
"""

import os
from typing import List, Tuple

# ======================
# 世界坐标与尺寸约定
# ======================

WALL_HEIGHT = 3.0
WALL_THICKNESS = 0.3
CORRIDOR_WIDTH = 2.5

FLOOR_Y = 0.0
FLOOR_THICKNESS = 0.1

ASSET_DIR = "assets/models/"

# ======================
# OBJ 数据结构 - MVP简化版
# ======================

class OBJMesh:
    """OBJ网格数据结构 - 最小可用实现"""
    
    def __init__(self, name: str):
        self.name = name
        self.vertices: List[Tuple[float, float, float]] = []  # [(x, y, z), ...]
        
        # 明确语义：faces 只存 (vertex_index1, vertex_index2, vertex_index3, material_name)
        # 索引从0开始（内部存储），导出时转为1-based（OBJ标准）
        self.faces: List[Tuple[int, int, int, str]] = []
        
        # 材质管理：每个面绑定一个材质
        self.materials: Set[str] = set()

# ======================
# 基础几何生成函数 - MVP简化版
# ======================

def add_box(mesh: OBJMesh, center, size, material):
    """
    生成一个轴对齐长方体（AABB）
    - center: (cx, cy, cz)
    - size: (sx, sy, sz)
    """
    cx, cy, cz = center
    sx, sy, sz = size

    hx, hy, hz = sx / 2, sy / 2, sz / 2

    # 8 个顶点
    v = [
        (cx - hx, cy - hy, cz - hz),
        (cx + hx, cy - hy, cz - hz),
        (cx + hx, cy + hy, cz - hz),
        (cx - hx, cy + hy, cz - hz),
        (cx - hx, cy - hy, cz + hz),
        (cx + hx, cy - hy, cz + hz),
        (cx + hx, cy + hy, cz + hz),
        (cx - hx, cy + hy, cz + hz),
    ]

    start_index = len(mesh.vertices)  # 应该是当前顶点数量，不是+1
    mesh.vertices.extend(v)

    # 12 个三角形（两个一组，组成一个面）
    faces = [
        # front (-Z)
        (0, 1, 2), (0, 2, 3),
        # back (+Z)
        (4, 6, 5), (4, 7, 6),
        # left (-X)
        (0, 3, 7), (0, 7, 4),
        # right (+X)
        (1, 5, 6), (1, 6, 2),
        # top (+Y)
        (3, 2, 6), (3, 6, 7),
        # bottom (-Y)
        (0, 4, 5), (0, 5, 1),
    ]

    for a, b, c in faces:
        mesh.faces.append((
            start_index + a + 1,  # OBJ是1-based索引
            start_index + b + 1,
            start_index + c + 1,
            material
        ))

def add_floor_plane(mesh: OBJMesh, center_x, center_z, width, depth, material):
    """
    生成 y = 0 的地面矩形（2 个三角形）
    """
    hx = width / 2
    hz = depth / 2
    y = 0.0

    v = [
        (center_x - hx, y, center_z - hz),
        (center_x + hx, y, center_z + hz),
        (center_x + hx, y, center_z - hz),
        (center_x - hx, y, center_z + hz),
    ]

    start_index = len(mesh.vertices)  # 应该是当前顶点数量，不是+1
    mesh.vertices.extend(v)

    # 两个三角形（注意：正确的顶点连接顺序）
    # 第一个三角形：v0 -> v1 -> v2
    # 第二个三角形：v0 -> v2 -> v3
    mesh.faces.append((start_index + 1, start_index + 2, start_index + 3, material))
    mesh.faces.append((start_index + 1, start_index + 3, start_index + 4, material))

# ======================
# OBJ 导出函数 - MVP简化版
# ======================

def export_obj(mesh: OBJMesh, filepath: str):
    os.makedirs(os.path.dirname(filepath), exist_ok=True)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(f"# OBJ generated by build_maze_geometry.py\n")
        f.write(f"o {mesh.name}\n\n")

        # 写顶点
        for v in mesh.vertices:
            f.write(f"v {v[0]} {v[1]} {v[2]}\n")

        f.write("\n")

        current_material = None
        for i1, i2, i3, material in mesh.faces:
            if material != current_material:
                f.write(f"usemtl {material}\n")
                current_material = material
            f.write(f"f {i1} {i2} {i3}\n")

# ======================
# 迷宫结构构建函数
# ======================

def build_start_area(mesh_walls: OBJMesh, mesh_floor: OBJMesh):
    """构建起点区域"""
    # 地面 (6x6)
    add_floor_plane(mesh_floor, 0, 0, 6, 6, "FLOOR_GROUND")
    
    # 围墙（留+X方向出口）
    add_box(mesh_walls, (0, WALL_HEIGHT/2, 3), (6, WALL_HEIGHT, WALL_THICKNESS), "WALL_STONE")  # 北墙
    add_box(mesh_walls, (0, WALL_HEIGHT/2, -3), (6, WALL_HEIGHT, WALL_THICKNESS), "WALL_STONE")  # 南墙
    add_box(mesh_walls, (-3, WALL_HEIGHT/2, 0), (WALL_THICKNESS, WALL_HEIGHT, 6), "WALL_STONE")  # 西墙

def build_main_corridor(mesh_walls: OBJMesh, mesh_floor: OBJMesh):
    """构建主通道1（教学走廊）"""
    corridor_length = 10
    corridor_center_x = 3 + corridor_length / 2
    
    # 地面
    add_floor_plane(mesh_floor, corridor_center_x, 0, corridor_length, CORRIDOR_WIDTH, "FLOOR_GROUND")
    
    # 左右墙
    wall_z_offset = CORRIDOR_WIDTH / 2 + WALL_THICKNESS / 2
    add_box(mesh_walls, (corridor_center_x, WALL_HEIGHT/2, -wall_z_offset), 
            (corridor_length, WALL_HEIGHT, WALL_THICKNESS), "WALL_STONE")  # 左墙
    add_box(mesh_walls, (corridor_center_x, WALL_HEIGHT/2, wall_z_offset), 
            (corridor_length, WALL_HEIGHT, WALL_THICKNESS), "WALL_STONE")  # 右墙

def build_torch_zone(mesh_floor: OBJMesh, mesh_torch: OBJMesh):
    """构建火把教学区"""
    # 火把基座（小立方体）
    torch_position = (13, 0.6, 0)  # 稍微抬高
    torch_size = (0.5, 1.2, 0.5)
    add_box(mesh_torch, torch_position, torch_size, "EMISSIVE_TORCH")
    
    # 连接区域的地面
    add_floor_plane(mesh_floor, 13, 0, 4, 4, "FLOOR_GROUND")

def build_dead_end(mesh_walls: OBJMesh, mesh_floor: OBJMesh):
    """构建假路（死路）"""
    dead_end_length = 6
    dead_end_center_z = dead_end_length / 2
    
    # 地面
    add_floor_plane(mesh_floor, 10, dead_end_center_z, CORRIDOR_WIDTH, dead_end_length, "FLOOR_GROUND")
    
    # 左右墙
    wall_x_offset = CORRIDOR_WIDTH / 2 + WALL_THICKNESS / 2
    add_box(mesh_walls, (10 - wall_x_offset, WALL_HEIGHT/2, dead_end_center_z), 
            (WALL_THICKNESS, WALL_HEIGHT, dead_end_length), "WALL_STONE")  # 左墙
    add_box(mesh_walls, (10 + wall_x_offset, WALL_HEIGHT/2, dead_end_center_z), 
            (WALL_THICKNESS, WALL_HEIGHT, dead_end_length), "WALL_STONE")  # 右墙
    
    # 末端封墙
    add_box(mesh_walls, (10, WALL_HEIGHT/2, dead_end_length), 
            (CORRIDOR_WIDTH + WALL_THICKNESS * 2, WALL_HEIGHT, WALL_THICKNESS), "WALL_STONE")

def build_pressure_plate_zone(mesh_floor: OBJMesh, mesh_plate: OBJMesh):
    """构建压力板区"""
    # 压力板（稍微高于地面）
    plate_position = (16, 0.1, -4)
    plate_size = (1.5, 0.2, 1.5)
    add_box(mesh_plate, plate_position, plate_size, "PLATE_METAL")
    
    # 连接区域的地面
    add_floor_plane(mesh_floor, 16, -4, 4, 4, "FLOOR_GROUND")

def build_gate_zone(mesh_gate: OBJMesh):
    """构建铁门区"""
    # 铁门（完全挡路）
    gate_position = (18, WALL_HEIGHT/2, -4)
    gate_size = (2.5, 3.0, 0.3)
    add_box(mesh_gate, gate_position, gate_size, "METAL_GATE")

def build_core_and_end(mesh_walls: OBJMesh, mesh_floor: OBJMesh):
    """构建核心区 + 终点区"""
    # 核心区地面 (8x8)
    add_floor_plane(mesh_floor, 22, -4, 8, 8, "FLOOR_GROUND")
    
    # 核心区围墙
    add_box(mesh_walls, (22, WALL_HEIGHT/2, 0), (8, WALL_HEIGHT, WALL_THICKNESS), "WALL_STONE")  # 北墙
    add_box(mesh_walls, (22, WALL_HEIGHT/2, -8), (8, WALL_HEIGHT, WALL_THICKNESS), "WALL_STONE")  # 南墙
    add_box(mesh_walls, (18, WALL_HEIGHT/2, -4), (WALL_THICKNESS, WALL_HEIGHT, 8), "WALL_STONE")  # 西墙
    add_box(mesh_walls, (26, WALL_HEIGHT/2, -4), (WALL_THICKNESS, WALL_HEIGHT, 8), "WALL_STONE")  # 东墙
    
    # 终点区地面 (6x6)
    add_floor_plane(mesh_floor, 30, -4, 6, 6, "FLOOR_GROUND")
    
    # 终点区围墙（无出口）
    add_box(mesh_walls, (30, WALL_HEIGHT/2, -1), (6, WALL_HEIGHT, WALL_THICKNESS), "WALL_STONE")  # 北墙
    add_box(mesh_walls, (30, WALL_HEIGHT/2, -7), (6, WALL_HEIGHT, WALL_THICKNESS), "WALL_STONE")  # 南墙
    add_box(mesh_walls, (27, WALL_HEIGHT/2, -4), (WALL_THICKNESS, WALL_HEIGHT, 6), "WALL_STONE")  # 西墙
    add_box(mesh_walls, (33, WALL_HEIGHT/2, -4), (WALL_THICKNESS, WALL_HEIGHT, 6), "WALL_STONE")  # 东墙

# ======================
# 主函数
# ======================

def main():
    """一键生成所有 OBJ 文件"""
    print("=== MazeGame 程序化建模工具 - MVP版本 ===")
    print("开始生成迷宫几何模型...\n")
    
    # 初始化 mesh
    maze_walls = OBJMesh("maze_walls")
    maze_floor = OBJMesh("maze_floor")
    torch_mesh = OBJMesh("torch_holder")
    plate_mesh = OBJMesh("pressure_plate")
    gate_mesh = OBJMesh("door_gate")
    
    # 构建迷宫
    print("构建起点区...")
    build_start_area(maze_walls, maze_floor)
    
    print("构建主通道...")
    build_main_corridor(maze_walls, maze_floor)
    
    print("构建火把区...")
    build_torch_zone(maze_floor, torch_mesh)
    
    print("构建假路...")
    build_dead_end(maze_walls, maze_floor)
    
    print("构建压力板区...")
    build_pressure_plate_zone(maze_floor, plate_mesh)
    
    print("构建铁门区...")
    build_gate_zone(gate_mesh)
    
    print("构建核心区与终点区...")
    build_core_and_end(maze_walls, maze_floor)
    
    # 导出 OBJ
    print("\n导出OBJ文件...")
    export_obj(maze_walls, ASSET_DIR + "maze_walls.obj")
    export_obj(maze_floor, ASSET_DIR + "maze_floor.obj")
    export_obj(torch_mesh, ASSET_DIR + "torch_holder.obj")
    export_obj(plate_mesh, ASSET_DIR + "pressure_plate.obj")
    export_obj(gate_mesh, ASSET_DIR + "door_gate.obj")
    
    print("\n🎉 迷宫几何模型生成完成！")
    print(f"- 墙壁模型: {len(maze_walls.vertices)} 顶点, {len(maze_walls.faces)} 面")
    print(f"- 地面模型: {len(maze_floor.vertices)} 顶点, {len(maze_floor.faces)} 面")
    print(f"- 火把模型: {len(torch_mesh.vertices)} 顶点, {len(torch_mesh.faces)} 面")
    print(f"- 压力板: {len(plate_mesh.vertices)} 顶点, {len(plate_mesh.faces)} 面")
    print(f"- 铁门: {len(gate_mesh.vertices)} 顶点, {len(gate_mesh.faces)} 面")

if __name__ == "__main__":
    main()